---
- name: Restart ovirt-engine
  ansible.builtin.systemd:
    name: "{{ olvm_engine_service }}"
    state: restarted

- name: Reload firewalld
  ansible.builtin.systemd:
    name: "{{ olvm_firewall_service }}"
    state: reloaded
